version: "3"

dotenv: ['./tf/.env']

includes:
  tf:
    taskfile: ./tf/TofuTasks.yml

tasks:
  test:
    desc: Run all tests (Ansible, Terraform)
    cmds:
      - task: test:ansible
      - task: tf:init
      - task: tf:validate

  test:ansible:
    desc: Run ansible-lint on playbooks
    cmds:
      - ansible-lint ansible/playbooks/
    silent: true

  lint:
    desc: Run pre-commit hooks on all files (auto-fixes where possible)
    cmds:
      - task: tf:fmt
      - pre-commit run --all-files

  ci:
    desc: Run tests and linting in Docker
    cmds:
      - docker build -t droplet .
      - docker run --rm droplet
