version: "3"

dotenv: ['.env']

tasks:
  tf-apply:
    cmds:
      - tofu apply
  tf-destroy:
    cmds:
      - tofu destroy
  tf-fmt:
    cmds:
      - tofu fmt .
  tf-init:
    cmds:
      - tofu init
  tf-plan:
    cmds:
      - tofu plan
  tf-providers-lock:
    cmds:
      - |
        tofu providers lock \
        -platform=darwin_amd64 \
        -platform=darwin_arm64 \
        -platform=linux_amd64
  tf-validate:
    cmds:
      - tofu validate
