---
- name: Provision host
  hosts: all
  become: true
  gather_facts: true

  vars:
    sites_available: "{{ (lookup('file', host_config_file) | from_yaml).sites }}"
    wordpress_prefix: "wp_"
    database_prefix: "db_"

  pre_tasks:
    - name: Capture SSH user
      ansible.builtin.set_fact:
        ssh_user: "{{ ansible_user }}"

  tasks:
    - name: Packages
      ansible.builtin.import_tasks: tasks/packages.yml
    - name: Firewall
      ansible.builtin.import_tasks: tasks/firewall.yml
    - name: Users
      ansible.builtin.import_tasks: tasks/users.yml
    - name: Docker
      ansible.builtin.import_tasks: tasks/docker.yml
    - name: WordPress
      ansible.builtin.import_tasks: tasks/wordpress.yml
