---
- name: Provision host
  hosts: all
  become: true
  gather_facts: true

  vars:
    sites_available: "{{ lookup('file', playbook_dir + '/../../tf/sites-available.json') | from_json }}"
    wordpress_prefix: "wp_"
    database_prefix: "db_"

  pre_tasks:
    - name: Capture SSH user
      ansible.builtin.set_fact:
        ssh_user: "{{ ansible_user }}"

  tasks:
    - name: Packages
      ansible.builtin.import_tasks: tasks/packages.yml
    - name: SSH
      ansible.builtin.import_tasks: tasks/ssh.yml
    - name: Firewall
      ansible.builtin.import_tasks: tasks/firewall.yml
    - name: Timezone
      ansible.builtin.import_tasks: tasks/timezone.yml
    - name: Hostname
      ansible.builtin.import_tasks: tasks/hostname.yml
    - name: Docker
      ansible.builtin.import_tasks: tasks/docker.yml

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted

    - name: Apply sysctl
      ansible.builtin.command:
        cmd: sysctl --system
      changed_when: true
