---
- name: Provision host
  hosts: all
  become: true
  gather_facts: true

  vars:
    sites_available: "{{ lookup('file', playbook_dir + '/../../tf/sites-available.json') | from_json }}"
    wordpress_prefix: "wp_"
    database_prefix: "db_"

  pre_tasks:
    - name: Capture SSH user
      ansible.builtin.set_fact:
        ssh_user: "{{ ansible_user }}"

  tasks:
    - name: Docker
      ansible.builtin.import_tasks: tasks/docker.yml
