---
- name: Add Docker GPG key
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg | \
    gpg --dearmor | \
    tee /usr/share/keyrings/docker.gpg > /dev/null
  args:
    creates: /usr/share/keyrings/docker.gpg

- name: Get dpkg architecture
  ansible.builtin.command:
    cmd: dpkg --print-architecture
  register: dpkg_architecture
  changed_when: false

- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ dpkg_architecture.stdout }}
      signed-by=/usr/share/keyrings/docker.gpg]
      https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}
      {{ ansible_facts['distribution_release'] }} stable
    filename: docker
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ssh_user }}"
    groups: docker
    append: true
