---
- name: Disable UFW before configuration
  ansible.builtin.command:
    cmd: ufw disable
  changed_when: true

- name: Deny default SSH port
  ansible.builtin.command:
    cmd: ufw deny ssh
  changed_when: true

- name: Allow SSH on port 4444
  ansible.builtin.command:
    cmd: ufw allow 4444/tcp
  changed_when: true

- name: Allow HTTP
  ansible.builtin.command:
    cmd: ufw allow http
  changed_when: true

- name: Allow HTTPS
  ansible.builtin.command:
    cmd: ufw allow https
  changed_when: true

- name: Enable UFW logging
  ansible.builtin.command:
    cmd: ufw logging on
  changed_when: true

- name: Enable UFW
  ansible.builtin.command:
    cmd: ufw --force enable
  changed_when: true
