---
- name: Allow hostname modification
  ansible.builtin.command:
    cmd: chattr -i /etc/hostname
  changed_when: true
  failed_when: false

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ droplet_hostname }}"

- name: Lock hostname
  ansible.builtin.command:
    cmd: chattr +i /etc/hostname
  changed_when: true
