---
- name: Update apt cache and upgrade packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    cache_valid_time: 3600

- name: Install packages
  ansible.builtin.apt:
    name:
      - auditd
      - fail2ban
      - gnupg
      - ufw
      - unattended-upgrades
      - zsh
    state: present

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot if required
  ansible.builtin.reboot:
    reboot_timeout: 300
  when: reboot_required.stat.exists

- name: Configure automatic updates
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: '0644'
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";

- name: Enable all update origins in unattended-upgrades
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^//\s*"\$\{distro_id\}:\$\{distro_codename\}-updates"'
    line: "\t\"${distro_id}:${distro_codename}-updates\";"

- name: Enable and start auditd
  ansible.builtin.systemd:
    name: auditd
    enabled: true
    state: started

- name: Enable and start unattended-upgrades
  ansible.builtin.systemd:
    name: unattended-upgrades
    enabled: true
    state: started

- name: Enable and start fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: started
