---
- name: Set timezone
  ansible.builtin.command:
    cmd: "timedatectl set-timezone {{ timezone | default('America/New_York') }}"
  changed_when: true

- name: Restart cron
  ansible.builtin.service:
    name: cron
    state: restarted
